spring:
  config:
    import: classpath:application-common.yml
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      #IP máy chủ Redis
      host: 127.0.0.1
      #Cổng kết nối Redis
      port: 6379
      #Mật khẩu kết nối Redis
      password: ${SPRING_DATA_REDIS_PASSWORD}
      #Thời gian chờ kết nối (mili giây)
      timeout: 10000

logging:
  level:
    root: error
    com.java2nb: error



content:
  save:
    storage: db #Phương tiện lưu trữ: db cơ sở dữ liệu, file văn bản TXT
    path: /Users/xiongxiaoyang/books  #Đường dẫn lưu nội dung tác phẩm TXT

# Cấu hình proxy HTTP
http:
  proxy:
    # Bật proxy HTTP: true bật, false tắt
    enabled: false
    # IP proxy
    ip: 40.83.102.86
    # Cổng proxy
    port: 80



