spring:
  config:
    import: classpath:application-common.yml
  main:
    allow-bean-definition-overriding: true
  #IP máy chủ Redis
  data:
    redis:
      host: 127.0.0.1
      #Cổng kết nối Redis
      port: 6379
      #Mật khẩu kết nối Redis
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      #Thời gian chờ kết nối (mili giây)
      timeout: 10000

content:
  save:
    storage: db # Cách lưu nội dung: db cơ sở dữ liệu, txt văn bản TXT
    path: /Users/xiongxiaoyang/books  # Đường dẫn lưu văn bản TXT của tác phẩm

# Cấu hình proxy HTTP
http:
  proxy:
    # Bật proxy HTTP: true bật, false tắt
    enabled: false
    # IP proxy
    ip: proxy.bestproxy.com
    # Cổng proxy
    port: 2312
    # Tên người dùng proxy
    username: ${HTTP_PROXY_USERNAME:}
    # Mật khẩu proxy
    password: ${HTTP_PROXY_PASSWORD:}
