#OSS
novel:
  file:
    endpoint: ${OSS_ENDPOINT:disabled} #Địa chỉ thay đổi theo khu vực máy chủ
    key-id: ${OSS_KEY_ID:disabled} #Lấy từ bảng điều khiển OSS
    key-secret: ${OSS_KEY_SECRET:disabled} #Lấy từ bảng điều khiển OSS
    bucket-name: ${OSS_BUCKET_NAME:disabled} #Tên bucket do bạn tạo bằng bảng điều khiển hoặc mã
    file-host: ${OSS_FILE_HOST:pic} #Đường dẫn tệp
    web-url: ${OSS_WEB_URL:http://localhost:8083/pic} #Địa chỉ web truy cập tệp OSS
