server:
  session-timeout: 18000
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  port: 80
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  datasource:
    driverClassName: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:absolutepath:${user.dir}/config/shardingsphere-jdbc.yml
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  
  #Kích thước tệp tải lên tối đa (100 MB)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  main:
    allow-bean-definition-overriding: true

mybatis:
  configuration:
    #Tự ánh xạ cột có dấu gạch dưới sang thuộc tính camelCase của Java
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.java2nb.**.domain

logging:
  config: classpath:logback-boot.xml
