java2nb:
  uploadPath: ${JAVA2NB_UPLOAD_PATH:/var/pic/}
logging:
  level:
    root: info
    com.java2nb: debug
spring:
  redis:
    host: ${SPRING_REDIS_HOST:127.0.0.1}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    # Thời gian chờ kết nối (mili giây)
    timeout: 10000
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 10s


